language: python
git:
  depth: 1
python:
  - "3.4"
install:
  - pip3 install homeassistant==0.49.0
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv shell_command_sample.yml shell_command.yml 
