- alias: Eco mode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.eco_mode
    state: 'on'  
  action:
    - service: switch.turn_off
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: eco

- alias: Comfort mode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.eco_mode
    state: 'off'  
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: heat

- alias: Turn off Eco mode at 4 PM
  initial_state: true
  trigger:
    platform: time
    at: '16:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: heat

- alias: Heal ZWave Nightly
  initial_state: true
  trigger:
    platform: time
    at: '2:31:00'
  action:
    - service: zwave.heal_network

- alias: Master outside light - 15 min timer 
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.master_outside_light_switch 
    to: 'on'
    for:
      minutes: 15
  action:
    - service: switch.turn_off
      entity_id: switch.master_outside_light_switch 

- alias: Nest set to away
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
  action:
    - service: shell_command.away_mode_on
    - service: switch.turn_off
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch

- alias: Nest set to home
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'off') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch

- alias: "Sunset"
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'  
  action:
    - service: switch.turn_on
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_on
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_on
      entity_id: switch.shop_outside_light_switch 
    - service: switch.turn_on
      entity_id: switch.fish_tank_light

- alias: "Sunrise"
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_off
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_off
      entity_id: switch.shop_outside_light_switch 
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

- alias: "Fish tank light at 6 AM"
  initial_state: true
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
  trigger:
     platform: time
     at: "06:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank_light

- alias: "Fish tank off at 10 PM"
  initial_state: true
  trigger:
     platform: time
     at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

