- alias: Heal ZWave Nightly
  initial_state: true
  trigger:
    platform: time
    at: '2:31:00'
  action:
    - service: zwave.heal_network

- alias: Notifcation that Nest has set away mode
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
  action:
    service: shell_command.away_mode_on

- alias: "Sunset - exterior lights"
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'  
  action:
    - service: switch.turn_on
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_on
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_on
      entity_id: switch.shop_outside_light_switch 

- alias: "Sunrise - exterior lights"
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_off
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_off
      entity_id: switch.shop_outside_light_switch 

- alias: "Turn off fish tank light when it is light out"
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

- alias: "Turn on fish tank light when it is dark and it's 6 AM"
  initial_state: true
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
  trigger:
     platform: time
     at: "06:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.fish_tank_light

- alias: "Turn on fish tank light when it is dark"
  initial_state: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank_light

- alias: "Yet turn off fish tank light when it is 10 PM"
  initial_state: true
  trigger:
     platform: time
     at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

