- id: alert_when_enabled 
  alias: Alert when enabled
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door_1_sensor 
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_door_2_sensor 
      from: 'off'
      to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.enable_alerts
      state: 'on'
  action:
    - service: shell_command.garage_opened

############################################################################
# GOAL: Enter through garage, enabled 60 minute timer for overhead lights  #
############################################################################


# Store value when ether door opens
- id : set_garage_light_timer_60_minutes
  alias: Garage light timers - 10 min timer
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door_1_sensor 
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_door_2_sensor 
      to: 'on'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.garage_value_storage
    
- id: turn_on_garage_lights
  alias: Storage for garage light timer 
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.garage_value_storage
    state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.garage_light_1_switch 
    - service: switch.turn_on
      entity_id: switch.garage_light_2_switch

# Set timer with light turning on AND garage_light_bool on
- id: set_garage_light_timer 
  alias: Turn off lights after 60 minutes 
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.garage_light_1_switch
      to: 'on'
      for:
        minutes: 60
    - platform: state
      entity_id: switch.garage_light_2_switch
      to: 'on'
      for:
        minutes: 60
  condition: 
    - condition: state
      entity_id: input_boolean.garage_value_storage
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.garage_light_1_switch
    - service: switch.turn_off
      entity_id: switch.garage_light_2_switch
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.garage_value_storage

############################################################################
# / GOAL                                                                   #
############################################################################

############################################################################
# Turn off Garage lights at 10 PM                                          #
############################################################################

- id: turn_off_garage_lights_at_10pm
  alias: Turn off Eco mode at 10 PM
  initial_state: true
  trigger:
    - platform: time
      at: '22:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.garage_light_1_switch
    - service: switch.turn_off
      entity_id: switch.garage_light_2_switch

############################################################################
# / GOAL                                                                   #
############################################################################

############################################################################
# Switch to turn off devices while I'm working from home till 4 PM         #
# Depends on input_boolean seen in configuration.yaml                      #
############################################################################

- id: eco_mode
  alias: Eco mode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.eco_mode_till_4_pm
    state: 'on'  
  action:
    - service: switch.turn_off
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: eco

- id: comfort_mode
  alias: Comfort mode
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.eco_mode_till_4_pm
    state: 'off'  
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: heat

- id: turn_off_eco_at_4pm
  alias: Turn off Eco mode at 4 PM
  initial_state: true
  trigger:
    - platform: time
      at: '16:00:00'
  condition: 
    - condition: state
      entity_id: input_boolean.eco_mode_till_4_pm
      state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: heat
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.eco_mode_till_4_pm

############################################################################
# / GOAL                                                                   #
############################################################################

- id: heal_zwave
  alias: Heal ZWave Nightly
  initial_state: true
  trigger:
    platform: time
    at: '2:31:00'
  action:
    - service: zwave.heal_network

- id: master_outside_light_15min
  alias: Master outside light - 15 min timer 
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.master_outside_light_switch 
    to: 'on'
    for:
      minutes: 15
  action:
    - service: switch.turn_off
      entity_id: switch.master_outside_light_switch 

- id: nest_set_away
  alias: Nest set to away
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'on') }}"
  action:
    - service: switch.turn_off
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch

- id: nest_set_home
  alias: Nest set to home
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ is_state_attr('climate.hallway', 'away_mode', 'off') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.aeotec_dsc06106_smart_energy_switch_switch

- id: sunset
  alias: "Sunset"
  initial_state: true
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'  
  action:
    - service: switch.turn_on
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_on
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_on
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_on
      entity_id: switch.shop_outside_light_switch 
    - service: switch.turn_on
      entity_id: switch.fish_tank_light

- id: sunrise
  alias: "Sunrise"
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'  
  action:
    - service: switch.turn_off
      entity_id: switch.garage_door_lights_switch 
    - service: switch.turn_off
      entity_id: switch.front_door_light_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_1_switch 
    - service: switch.turn_off
      entity_id: switch.porch_light_2_switch 
    - service: switch.turn_off
      entity_id: switch.shop_outside_light_switch 
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

- id: fish_tank_6am
  alias: "Fish tank light at 6 AM"
  initial_state: true
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
  trigger:
     platform: time
     at: "06:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.fish_tank_light

- id: fish_tank_10pm
  alias: "Fish tank off at 10 PM"
  initial_state: true
  trigger:
     platform: time
     at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.fish_tank_light

