homeassistant:
  name: !secret home_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml

frontend:
  themes: !include theme_midnight.yaml

config:

http:
  api_password: !secret api_password

discovery:

history:

logbook:

sun:

input_boolean:
  eco_mode_till_4_pm:
      name: Eco mode till 4 PM
      initial: off
      icon: mdi:leaf
  enable_alerts:
      name: Enable away alerts
      initial: off
      icon: mdi:message-alert
  msg_on_unique_behavior:
      name: Interesting Behavior
      initial: on
      icon: mdi:message-alert
  garage_value_storage:
      name: Garage value storage
      initial: off

camera:
  - platform: uvc
    nvr: !secret uvc_server
    key: !secret uvc_api

ios:

zone: !include zone.yaml

sensor: !include sensor.yaml

sensor slushpool_status:
   - platform: rest
     name: Slushpool Confirmed Rewards
     resource: !secret slushpool_resource 
     value_template: '{{ value_json.confirmed_reward }}'

device_tracker: !include device_tracker.yaml

zwave: !include zwave.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# shell_command: !include shell_command.yml

group: !include groups.yaml
automation: !include automations.yaml
