homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name 
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation 
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone 
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password 

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: moon
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - cloudiness
  - platform: openweathermap
    forecast: True
    api_key: !secret openweathermap_api 
  - platform: wunderground
    api_key: b65d0586d56ba400 
    monitored_conditions:
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n

amcrest:
  - host: 10.0.1.51
    username: admin
    password: !secret camera_password 
    resolution: high 
    stream_source: rtsp
  - host: 10.0.1.52
    username: admin
    password: !secret camera_password 
    resolution: high
    stream_source: rtsp
  - host: 10.0.1.53
    username: admin
    password: !secret camera_password 
    resolution: high
    stream_source: rtsp

camera:
  - platform: amcrest

device_tracker:
  - platform: unifi
    host: 10.0.1.2
    username: !secret unifi_user
    password: !secret unifi_pw
    site_id: default
    verify_ssl: 'False'

zwave:
    usb_path: /dev/ttyUSB0

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#zoneminder:
#  host: 10.0.1.21
#  host: !secret zm_host 
#  path: !secret zm_path
#  path_zms: !secret zms_path 
#  ssl: True
#  username: !secret zm_user 
#  password: !secret zm_pass 

shell_command: !include shell_command.yml

group: !include groups.yaml
automation: !include automations.yaml
